// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OnEp1YIMtBIRsD-yvNBEsmf8Yw68zj8',
    appId: '1:615087575692:web:e6438b29f69e874f9d21a9',
    messagingSenderId: '615087575692',
    projectId: 'do-instead-firebase',
    authDomain: 'do-instead-firebase.firebaseapp.com',
    storageBucket: 'do-instead-firebase.firebasestorage.app',
    measurementId: 'G-XFH5QV1DK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83I-GbeiOiLUS8cBx6MhEqgw6gWL-dZk',
    appId: '1:615087575692:android:d563898ac7f7a17f9d21a9',
    messagingSenderId: '615087575692',
    projectId: 'do-instead-firebase',
    storageBucket: 'do-instead-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MbFaDZxdozO03K3b2leej3CKxb8mS_E',
    appId: '1:615087575692:ios:ef19283460b49c149d21a9',
    messagingSenderId: '615087575692',
    projectId: 'do-instead-firebase',
    storageBucket: 'do-instead-firebase.firebasestorage.app',
    iosBundleId: 'com.example.doInstead',
  );
}
